#! ruby
require 'test/unit'

class TestVersion < Test::Unit::TestCase
  def test_version
    version = '0.1.210625'
    assert_equal(version, `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' lib/*.rb`.split.first)
    assert_equal(version, `l4d2-observer --version`.strip)
    if gemspec = `ls *.gemspec 2> /dev/null`.split.first
      assert_equal(version, `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' #{gemspec}`.split.first)
    end
    if readme = `ls README.* 2> /dev/null`.split.first
      assert_equal(version, `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' #{readme}`.split.first)
    end
  end
end
