#!/usr/bin/env ruby
require 'test/unit'

class TestVersion < Test::Unit::TestCase
  def test_version
    version = `l4d2-observer --version`.strip
    v = `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' README.md`.split.first
    assert_equal(version, v)
  end
end
